### ISSUE TITLE
Add a function for /coins/{id}/market_chart coingecko endpoint

### ISSUE THREAD

**Issue by Niraj-Kamdar** [defiwrapper/defiwrapper#25]
For more details look at #4

**Comment by codeproline** [comment]
@Niraj-Kamdar  I am gonna do this ticket. @codeproline

**Comment by Niraj-Kamdar** [comment]
[Txn of $500](https://polygonscan.com/tx/0x4602d767ea5d1b585009685e588d11a137324e1e0c66725e1ad7b35a6d4bdb40) to @codeproline for closing the issue 👏 thanks again dude :)
