### ISSUE TITLE
.w3 folder not being built in Coingecko package 

### ISSUE THREAD

**Issue by rihp** [defiwrapper/defiwrapper#59]
Steps that outline how to create a new function on issue #4 has brought us some trouble.

Yarn build command is only building the defi-sdk folder instead of all of them. So for example to get w3 folder on Coingecko, you have to run it manually from the package's folder.

Thanks Juan for finding this and Kevin for helping debug. 👷‍♂️👷‍♂️

**Comment by rihp** [comment]
also, you might need to deploy the wrapper at coingecko.eth within the test-env

**Comment by Niraj-Kamdar** [comment]
We are deploying it at `coingecko.eth` So, it should be working.
